### ISSUE TITLE
不知道作者有没有考虑把自定义View更加灵活，不局限于只是图片，比如视频也可以用

### ISSUE THREAD

**Issue by dccice** [albert-lii/ImageViewer#11]

**Comment by albert-lii** [comment]
不好意思，最近出差较忙！
暂时还没有考虑视频这方面！视频涉及到的生命周期较复杂，且视频控件较多，每个人的选择都不同！如果你有这方面的需求：
1. 可以预先将你使用的video控件隐藏在imageView上面，待作为video封面的imageView执行完预览动画后，再显示出video控件
2. 在activity中获取video控件对象，操控更安全和便利
