### ISSUE TITLE
pointerIndex out of range

### ISSUE THREAD

**Issue by jefshi** [albert-lii/ImageViewer#12]
在 2.0.2 版本报一下错误，可以看看最新版本是否已经修复该BUG：

pointerIndex out of range
com.liyi.viewer.widget.ImagePager.onInterceptTouchEvent(ImagePager.java:68)

这是Bugly提供的解决方案，可以参考一下
参数不匹配异常，通常由于传递了不正确的参数导致。
常见于：
1. Activity、Service状态异常；
2. 非法URL；
3. UI线程操作。
4.Fragment中嵌套了子Fragment，Fragment被销毁，而内部Fragment未被销毁，所以导致再次加载时重复，在onDestroyView() 中将内部Fragment销毁即可
5.在请求网络的回调中使用了glide.into(view),view已经被销毁会导致该错误

**Comment by albert-lii** [comment]
你好，

谢谢你的反馈，因为最近项目较忙，刚刚看到，抱歉！

以上错误，是因为多点触控操作ImageView导致，在最新版本中已经做了相应处理！

如果仍然发现类似错误或者其他错误，欢迎 issue！
