### ISSUE TITLE
预览的时候图片模糊

### ISSUE THREAD

**Issue by sing1** [albert-lii/ImageViewer#15]
做压缩处理了吗？预览的时候很模糊

**Comment by albert-lii** [comment]
你好，谢谢你的反馈！
所有的图片加载是开发者自己操作的，ImageViewer中未做任何压缩相关处理！
如果图片模糊，应该是你使用的图片加载框架或者图片本身问题，例如加载的是缩略图，ImageViewer中仅仅是用ImageView控件去显示你给的图片资源，未做其他处理！
