### ISSUE TITLE
图片点击后打开，然后进行滑动，无法获取到下次滑动的位置在监听器里

### ISSUE THREAD

**Issue by hufu4635** [albert-lii/ImageViewer#16]
if (state == STATE_WATCHING) {
                    position = imagePager.getPosition();//图片滑动到下一张图片后 position还是首次点击图片打开的position
                }

**Comment by albert-lii** [comment]
WATCHING状态不是实时监听的，一般只在进场动画执行完毕后触发一次，此时的position为你点击图片的position，你可以在图片切换事件中监听position看看，另项目已更新至3.0版本。
