### ISSUE TITLE
图片模糊

### ISSUE THREAD

**Issue by oveeeee** [albert-lii/ImageViewer#18]
第一次加载图片时图片模糊，因为有开场动画的原因，如何修改这个问题

**Comment by oveeeee** [comment]
如何在动画结束后再加载图片

**Comment by albert-lii** [comment]
项目中目前的图片加载都是开发者自定义的，项目无法去干涉到图片的清晰度，你可以看一下你使用的图片加载框架是否对图片清晰度做了处理。另，如果要在动画结束后加载图片来解决图片清晰度的问题，你可以在动画结束后单独将item提出来重新设置图片资源。
