### ISSUE TITLE
不知道为啥，第一张图片会向下歪

### ISSUE THREAD

**Issue by YuShanMuGong** [albert-lii/ImageViewer#19]
![image](https://user-images.githubusercontent.com/13248312/52038037-df530880-256b-11e9-89e3-873dd4d28cee.png)

> 如图上面的照片本应该居中的，不知道咋的向下偏

**Comment by albert-lii** [comment]
你可以断点查看一下该图片的x与y轴的坐标，应该是你的坐标设置有误差，另项目已更新至3.0.0版本
