### ISSUE TITLE
有严重的内存泄露的问题。

### ISSUE THREAD

**Issue by zidanpiaoguo** [albert-lii/ImageViewer#2]
整体还不错，但是图片加载那一块，有很严重的内存泄露的问题。

**Comment by zidanpiaoguo** [comment]
希望能完善一下ImagePreviewActivity的一些注释，为什么有那么多加载图片的语句

**Comment by albert-lii** [comment]
已经全新改版，使用自定义View的模式实现，内有详细注释，图片加载已经放到外部可以自定义操作
