### ISSUE TITLE
一直双指放大会闪退

### ISSUE THREAD

**Issue by oveeeee** [albert-lii/ImageViewer#20]
一直双指放大会闪退

**Comment by albert-lii** [comment]
你好，能说明下具体的操作和提供下具体的错误吗，我在我的几个测试机上并未能重现，谢谢！

**Comment by oveeeee** [comment]
> 你好，能说明下具体的操作和提供下具体的错误吗，我在我的几个测试机上并未能重现，谢谢！

双指放大的时候，动作快的话会闪退。

**Comment by albert-lii** [comment]
谢谢，说明！bug已修复！
