### ISSUE TITLE
请问想要实现往上拖拽也可以退出预览，有什么方式吗？

### ISSUE THREAD

**Issue by bilx** [albert-lii/ImageViewer#21]
ps.首先感谢作者大佬的库，真的很好用
关于标题的问题，我现在想实现往上拖拽的时候也能够退出图片浏览，类似于微博的预览效果，请问有什么实现思路吗？

**Comment by albert-lii** [comment]
可以实现，代码中对agile模式的拖拽做了向上拖动退出做了限制，只需要去除就行，具体看源码中的DragHandler中agile模式拖拽的代码块
