### ISSUE TITLE
动态图预览无法正常播放

### ISSUE THREAD

**Issue by oveeeee** [albert-lii/ImageViewer#24]
动态图预览无法正常播放，第一次点击出来预览会变模糊

**Comment by albert-lii** [comment]
内部使用的图片控件是PhotoView，Gif图是可以正常播放的。图片预览和播放都是开发者自定义的，ImageViewer 并未做任何修改和限制，无妨播放动图和预览模糊应该是你使用的图片加载框架的配置出了点问题。
