### ISSUE TITLE
大佬,301版本依赖不到,只能依赖212版本

### ISSUE THREAD

**Issue by lydlovezjr** [albert-lii/ImageViewer#26]
<img width="880" alt="微信截图_20190603200017" src="https://user-images.githubusercontent.com/19246347/58800415-5c85ab80-863a-11e9-9c03-7039f39dd2dc.png">

**Comment by jianjunzhao-github** [comment]
allprojects {
    repositories {
        maven { url "https://dl.bintray.com/albertlii/android-maven/" }
    }
}
