### ISSUE TITLE
Eoor

### ISSUE THREAD

**Issue by OnlyYouMyLove** [albert-lii/ImageViewer#3]
Unable to start activity ComponentInfo{com.nijigenlink.gb/com.liyi.viewer.view.ImagePreviewActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class uk.co.senab.photoview.PhotoView

**Comment by albert-lii** [comment]
Activity模式的图片浏览是1.0版本的，现在已经换成2.0版本的自定义View的模式了，更加方便，灵活

**Comment by OnlyYouMyLove** [comment]
感谢，我已经集成到自己的项目中，非常好，可以关闭这个问题，用的是2.0的版本。
