### ISSUE TITLE
recyclerview

### ISSUE THREAD

**Issue by OnlyYouMyLove** [albert-lii/ImageViewer#4]
recyclerview使用的时候应该注意哪些问题呢，总是报空指针异常，求助 @albert-lii

**Comment by albert-lii** [comment]
你的意思是，点击grid形态的recyclerview中的图片，然后实现图片浏览效果吗？只要确定传入了图片的资源和子view的信息位置，其他和recyclerivew都没有什么必然的关系！

**Comment by OnlyYouMyLove** [comment]
横向recyclerview，item就是一个imageview，在position方面总是报越界，所以能否展示下，横向recyclerview方面如何使用你的库呢？这种横向的图片滑动，然后点击显示大图，可以以一种viewpager的形式滑动的方式，用的还是比较多的，最近能否抽空帮忙看下呢？感激不尽，盼复，祝好

**Comment by albert-lii** [comment]
recyclerview已经上传了一个例子，你看看是否是这种样式

**Comment by albert-lii** [comment]
已上传横向与纵向列表的例子
