### ISSUE TITLE
关于内存及时回收

### ISSUE THREAD

**Issue by OnlyYouMyLove** [albert-lii/ImageViewer#5]
因为展示的图片都是比较高清的，比如说demo中的6张图片，这个时候，打开自定义控件imageviewer后，内存会从100M飙升到180M，是不是应该在viewpager切换的过程中及时回收，这是第一个问题。第二个问题是退出imageviewer后，能否做到及时回收图片的内存呢？

技术探讨，可能和框架本身无关，也可能有关，让框架更完善，盼复，辛苦了，感谢你的分享，祝好。

**Comment by albert-lii** [comment]
谢谢你的建议，已对框架做内存优化，目前复用 Item，滑动切换和关闭时都会做内存回收处理！但是对于bitmap的recycle()操作，框架中未使用，因为测试中会出现 Canvas: trying to use a recycled bitmap异常，如有解决方法，欢迎告知，谢谢！

**Comment by OnlyYouMyLove** [comment]
辛苦，Good Job ！祝工作顺利！

在 2018-05-09 15:35:21，"Yi Li" <notifications@github.com> 写道：


谢谢你的建议，已对框架做内存优化，目前复用 Item，滑动切换和关闭时都会做内存回收处理！但是对于bitmap的recycle()操作，框架中未使用，因为测试中会出现 Canvas: trying to use a recycled bitmap异常，如有解决方法，欢迎告知，谢谢！

**Comment by OnlyYouMyLove** [comment]
点击返回键监听不到它的退出；所以导致点击返回键就退出了fragment，只给了正常退出的监听，这样不行，能否帮忙改进下，谢谢了。






在 2018-05-09 15:35:21，"Yi Li" <notifications@github.com> 写道：


谢谢你的建议，已对框架做内存优化，目前复用 Item，滑动切换和关闭时都会做内存回收处理！但是对于bitmap的recycle()操作，框架中未使用，因为测试中会出现 Canvas: trying to use a recycled bitmap异常，如有解决方法，欢迎告知，谢谢！

**Comment by OnlyYouMyLove** [comment]
这个问题，我已经解决了，主动设置隐藏和显示，然后获取它的状态，进行判断的。祝好。





在 2018-05-17 11:32:04，"付凯强" <18201685396@163.com> 写道：

点击返回键监听不到它的退出；所以导致点击返回键就退出了fragment，只给了正常退出的监听，这样不行，能否帮忙改进下，谢谢了。






在 2018-05-09 15:35:21，"Yi Li" <notifications@github.com> 写道：


谢谢你的建议，已对框架做内存优化，目前复用 Item，滑动切换和关闭时都会做内存回收处理！但是对于bitmap的recycle()操作，框架中未使用，因为测试中会出现 Canvas: trying to use a recycled bitmap异常，如有解决方法，欢迎告知，谢谢！

**Comment by OnlyYouMyLove** [comment]
Hi，非常感谢在工作之余开发的这款ImageViewer的框架，明天就是6月1日儿童节。祝节日快乐（借小朋友的节日送祝福）！


发现一个问题，就是setImageData这个Api的参数是一个List<Object>，我这里虽然重新创建一个List，还需要把List<String>的数据放进去，觉得实在是麻烦，可能你有其他考虑，不过建议能提供一个单独的Api，针对网络图片URL集合。


再次感谢你的无私奉献，祝工作顺利！

**Comment by albert-lii** [comment]
你好，感谢你的建议，最近因为工作关系没有关注github，近期会根据你的建议继续完善`Imageviewer`，谢谢你的建议！
