### ISSUE TITLE
查看大图时 出现黑屏后没有反应

### ISSUE THREAD

**Issue by tianshaokai** [albert-lii/ImageViewer#6]
1.是不是可以先加载小图然后放大呢，或者加一个加载效果

**Comment by albert-lii** [comment]
你好，这个以前是这么做的，但是考虑到每个人能使用的图片加载工具可能不同，所以图片加载是放在外部由开发者自定义加载的！
1、出现黑屏可能是你的图片加载框架未能加载出图片
2、先加载缩略图，然后加载大图是你直接在你自定义的图片加载框架中实现的，glide即可实现
3、加载效果同上，你在加载图片时可以自己设置一张占位图和加载失败图， 都是不受框架限制的

**Comment by tianshaokai** [comment]
不好意思，我是运行的demo

**Comment by albert-lii** [comment]
可以告知一下具体的现象以及操作流程吗？是偶发还是常现？谢谢

**Comment by tianshaokai** [comment]
点击简单预览，网络不好的情况下 进去就是黑色背景，也没有加载进度，也没有类似微信的那种小图显示，然后有个加载中效果

**Comment by tianshaokai** [comment]
可否改一下加载效果呢，作者的效果是手势向下滑动后关闭页面，而不是像微信效果 一样还能回到 原来位置 的 效果

**Comment by tianshaokai** [comment]
可否加作者一个 qq或者微信交流一下呢？

**Comment by tianshaokai** [comment]
竖向的demo 打开图片效果，  图片 如果在 顶部或者在底部 打开图片后再返回列表，图片都会强制滚动到中间

**Comment by albert-lii** [comment]
感谢你的建议，以下是针对你的建议的答复：
## 控件的本质：  
`ImageViewer`不负责图片的加载流程，其本质是对图片集的放大预览的控制，所有图片加载均根据项目实际情况进行自定义，demo中只是举例参考，不是标准  

## 对建议的回复
1、黑屏是因为我在demo中使用glide加载时，未设置占位图，在网络不稳定时未加载出图片，目前已添加，与控件本身无关，可放心使用，demo中加载方式只是参考，请根据自身项目实际情况设置加载模式

2、目前的加载效果是由于以前项目需要，仿照今日头条来做的，微信的效果可以实现，但是最近比较忙，可能得过些时间

3、竖向demo与横向demo在图片打开后，在返回列表，图片强制滚动到中间的效果只是个参照，主要告诉使用者如何在竖向和横向列表中使用控件，图片的强制滚动是与控件无关的，使用者可根据项目的实际状况来决定效果，以上效果只是我以前项目的需求，仅作参考  

最后，感谢你对项目的建议，如果感兴趣，也可一起参与对`ImageViewer`的构建，如需加qq或者微信，将联系方式发送到albertlii@163.com邮箱，我加你，一起学习进步！望回复！！！

**Comment by tianshaokai** [comment]
已经发给你 希望可以一起进步
