### ISSUE TITLE
首次打开会稍微抖动一下，第二次打开就不抖动了

### ISSUE THREAD

**Issue by Just2Archi** [albert-lii/ImageViewer#7]
场景：

原图尺寸：W=600px, H=800px
缩略图尺寸：W=600px, H=600px （缩略图为原图的中间部分）

列表上的使用的是缩略图，点击缩略图打开imageViewer（传入的是原图的URL），就会出现第一次会稍微有点抖动，不自然，但是第二次就好了。第二次好的原因是：

```kotlin
override fun onResourceReady(resource: Drawable, transition: Transition<in Drawable>?) {
    view.setImageDrawable(resource)

    // 把下面2行注释了后，第二次也会抖动。
    frames.get(position).setImageWidth(resource.intrinsicWidth.toFloat())
    frames.get(position).setImageHeight(resource.intrinsicHeight.toFloat())
}
```

**Comment by albert-lii** [comment]
抖动的是因为Imageviewer没有获取到目标view的图片宽高，ImageViewer的进场动画是根据图片宽高来实现的，如果在进场动画前，没有获取到图片宽高，会有些许不自然！
最新版的ImageViewer已做进一步优化！
